/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto.View;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author bruno
 */
public class InterfaceSistema extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceSistema
     */
    public InterfaceSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        pnlBarraLateral = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jifHome = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jifFilmes = new javax.swing.JInternalFrame();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnSalvar2 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        btnLimpar2 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        btnConsultar2 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        btnCancelar2 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSinopse = new javax.swing.JTextArea();
        jifClientes = new javax.swing.JInternalFrame();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btnSalvar1 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        btnConsultar1 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        btnLimpar1 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        ftxtDataNasc = new javax.swing.JFormattedTextField();
        jLabel69 = new javax.swing.JLabel();
        ftxtCPF = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jifAtores = new javax.swing.JInternalFrame();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtAtor = new javax.swing.JTextField();
        jcbNacionalidade = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jifLocacoes = new javax.swing.JInternalFrame();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnSalvar3 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        btnLimpar3 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        btnCancelar3 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        btnConsultar3 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        txtTituloItem = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel77 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Locadora Sessão Meia Noite");
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(25, 25, 25));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraLateral.setBackground(new java.awt.Color(30, 30, 30));
        pnlBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(25, 25, 25));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/moderator-24.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Atores");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 70, 40));

        pnlBarraLateral.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 160, 40));

        jPanel4.setBackground(new java.awt.Color(25, 25, 25));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/home-7-24.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Home");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 50, 40));

        pnlBarraLateral.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 40));

        jPanel5.setBackground(new java.awt.Color(25, 25, 25));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(153, 0, 0));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/film-reel-24.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Filmes");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 70, 40));

        pnlBarraLateral.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 160, 40));

        jPanel6.setBackground(new java.awt.Color(25, 25, 25));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(153, 0, 0));
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/user-24.png"))); // NOI18N
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Clientes");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 70, 40));

        pnlBarraLateral.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 160, 40));

        jPanel8.setBackground(new java.awt.Color(25, 25, 25));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/question-mark-4-32.png"))); // NOI18N
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        pnlBarraLateral.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 50, 40));

        jPanel9.setBackground(new java.awt.Color(25, 25, 25));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(153, 0, 0));
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/shopping-basket-2-24.png"))); // NOI18N
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jLabel20.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Itens");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        pnlBarraLateral.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 160, 40));

        jPanel10.setBackground(new java.awt.Color(24, 24, 24));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Locadora");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, -1));

        jLabel23.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Sessão Meia Noite");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 20));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/film-48.png"))); // NOI18N
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 70));

        pnlBarraLateral.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 130));

        jPanel16.setBackground(new java.awt.Color(20, 20, 20));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/gear-2-32.png"))); // NOI18N
        jPanel16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        pnlBarraLateral.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 50, 40));

        pnlBackground.add(pnlBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 530));

        jDesktopPane1.setBackground(new java.awt.Color(15, 15, 15));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jifHome.setTitle("Página Principal");
        jifHome.setVisible(true);
        jifHome.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(27, 25, 25));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Home");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/home-7-80.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 100));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setPreferredSize(new java.awt.Dimension(870, 440));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 870, 540));

        jifHome.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        jDesktopPane1.add(jifHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 880, 570));

        jifFilmes.setTitle("Catálogo de Filmes");
        jifFilmes.setVisible(false);
        jifFilmes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(33, 32, 32));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Filmes");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/film-reel-80.png"))); // NOI18N
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 100));

        btnSalvar2.setBackground(new java.awt.Color(35, 35, 35));
        btnSalvar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvar2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalvar2MousePressed(evt);
            }
        });
        btnSalvar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Salvar");
        btnSalvar2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/save-24.png"))); // NOI18N
        btnSalvar2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel11.add(btnSalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 160, 40));

        btnLimpar2.setBackground(new java.awt.Color(35, 35, 35));
        btnLimpar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpar2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLimpar2MousePressed(evt);
            }
        });
        btnLimpar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/polish-cloth-24.png"))); // NOI18N
        btnLimpar2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Limpar");
        btnLimpar2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jPanel11.add(btnLimpar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 160, 40));

        btnConsultar2.setBackground(new java.awt.Color(35, 35, 35));
        btnConsultar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultar2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConsultar2MousePressed(evt);
            }
        });
        btnConsultar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/search-3-24.png"))); // NOI18N
        btnConsultar2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Consultar");
        btnConsultar2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jPanel11.add(btnConsultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 160, 40));

        btnCancelar2.setBackground(new java.awt.Color(35, 35, 35));
        btnCancelar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelar2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelar2MousePressed(evt);
            }
        });
        btnCancelar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Cancelar");
        btnCancelar2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/x-mark-24.png"))); // NOI18N
        btnCancelar2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel11.add(btnCancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 160, 40));

        jLabel72.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Título: ");
        jPanel11.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, 20));

        jLabel73.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Gênero: ");
        jPanel11.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, 20));

        jLabel74.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Sinopse: ");
        jPanel11.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, 20));

        txtTitulo.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jPanel11.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 320, 30));

        txtGenero.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jPanel11.add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 320, 30));

        txaSinopse.setColumns(20);
        txaSinopse.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        txaSinopse.setRows(5);
        jScrollPane1.setViewportView(txaSinopse);

        jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 320, 130));

        jifFilmes.getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        jDesktopPane1.add(jifFilmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 880, 570));

        jifClientes.setTitle("Clientes");
        jifClientes.setMinimumSize(new java.awt.Dimension(880, 570));
        jifClientes.setPreferredSize(new java.awt.Dimension(886, 574));
        jifClientes.setVisible(false);
        jifClientes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(33, 32, 32));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Clientes");
        jPanel15.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/user-80.png"))); // NOI18N
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 100));

        jPanel21.setBackground(new java.awt.Color(51, 51, 51));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(33, 32, 32));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Atores");
        jPanel22.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/moderator-80.png"))); // NOI18N
        jPanel22.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 100));

        btnSalvar1.setBackground(new java.awt.Color(35, 35, 35));
        btnSalvar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalvar1MousePressed(evt);
            }
        });
        btnSalvar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Salvar");
        btnSalvar1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/save-24.png"))); // NOI18N
        btnSalvar1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel21.add(btnSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 160, 40));

        btnCancelar1.setBackground(new java.awt.Color(35, 35, 35));
        btnCancelar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/x-mark-24.png"))); // NOI18N
        btnCancelar1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Cancelar");
        btnCancelar1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jPanel21.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 160, 40));

        btnConsultar1.setBackground(new java.awt.Color(35, 35, 35));
        btnConsultar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Consultar");
        btnConsultar1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/search-3-24.png"))); // NOI18N
        btnConsultar1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel21.add(btnConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 160, 40));

        btnLimpar1.setBackground(new java.awt.Color(35, 35, 35));
        btnLimpar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Limpar");
        btnLimpar1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/polish-cloth-24.png"))); // NOI18N
        btnLimpar1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel21.add(btnLimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 160, 40));

        jLabel43.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Data de nascimento: ");
        jPanel21.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        jPanel21.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 350, -1));

        jLabel44.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Nome: ");
        jPanel21.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        try {
            ftxtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel21.add(ftxtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 70, -1));

        jLabel69.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("CPF: ");
        jPanel21.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        try {
            ftxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel21.add(ftxtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 80, -1));
        jPanel21.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 360, -1));

        jLabel70.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("E-mail: ");
        jPanel21.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));
        jPanel21.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 350, -1));

        jLabel71.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Endereço: ");
        jPanel21.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jPanel14.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        jifClientes.getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 570));

        jDesktopPane1.add(jifClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 880, 570));

        jifAtores.setTitle("Itens");
        jifAtores.setVisible(false);
        jifAtores.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(51, 51, 51));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(33, 32, 32));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Atores");
        jPanel18.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/moderator-80.png"))); // NOI18N
        jPanel18.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 100));

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nome do ator: ");
        jPanel17.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 110, 30));

        jLabel26.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nacionalidade: ");
        jPanel17.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 110, 30));

        txtAtor.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jPanel17.add(txtAtor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 490, 30));

        jcbNacionalidade.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jcbNacionalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a nacionalidade deste ator.", "Brasileiro", "Canadense", "Mexicano(a)", "Argentino(a)", "Italiano(a)", "Norte Americano(a)", "Inglês(esa)", "Francês(esa)", "Japonês(esa)", "Espanhol(a)", "Holandês(esa)", "Alemão", "Sueco(a)", "Chileno(a)", "Boliviano(a)", "Chinês", "Australiano(a)", "Jamaicano(a)", "Suiço(a)", "Iraquiano(a)", "Húngaro(a)", "Ruso(a)", "Belga", "Equatoriano(a)", "Turco(a)", "Paraguaio(a)", "Uraguaio(a)", "Cubano(a)", "Colombiano(a)" }));
        jPanel17.add(jcbNacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 360, 30));

        btnSalvar.setBackground(new java.awt.Color(35, 35, 35));
        btnSalvar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Salvar");
        btnSalvar.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/save-24.png"))); // NOI18N
        btnSalvar.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jPanel17.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 160, 40));

        btnLimpar.setBackground(new java.awt.Color(35, 35, 35));
        btnLimpar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Limpar");
        btnLimpar.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 0, 110, 40));

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/polish-cloth-24.png"))); // NOI18N
        btnLimpar.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jPanel17.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 160, 40));

        btnCancelar.setBackground(new java.awt.Color(35, 35, 35));
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Cancelar");
        btnCancelar.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/search-3-24.png"))); // NOI18N
        btnCancelar.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jPanel17.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 160, 40));

        btnConsultar.setBackground(new java.awt.Color(35, 35, 35));
        btnConsultar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Consultar");
        btnConsultar.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/search-3-24.png"))); // NOI18N
        btnConsultar.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jPanel17.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 160, 40));

        jifAtores.getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        jDesktopPane1.add(jifAtores, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 880, 570));

        jifLocacoes.setTitle("Locações");
        jifLocacoes.setVisible(false);
        jifLocacoes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(51, 51, 51));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(33, 32, 32));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Itens");
        jPanel20.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/shopping-basket-2-80.png"))); // NOI18N
        jPanel20.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 100));

        btnSalvar3.setBackground(new java.awt.Color(35, 35, 35));
        btnSalvar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Salvar");
        btnSalvar3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/save-24.png"))); // NOI18N
        btnSalvar3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel19.add(btnSalvar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 160, 40));

        btnLimpar3.setBackground(new java.awt.Color(35, 35, 35));
        btnLimpar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Cancelar");
        btnLimpar3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/x-mark-24.png"))); // NOI18N
        btnLimpar3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel19.add(btnLimpar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 160, 40));

        btnCancelar3.setBackground(new java.awt.Color(35, 35, 35));
        btnCancelar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/search-3-24.png"))); // NOI18N
        btnCancelar3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Consultar");
        btnCancelar3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jPanel19.add(btnCancelar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 160, 40));

        btnConsultar3.setBackground(new java.awt.Color(35, 35, 35));
        btnConsultar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/ícones/polish-cloth-24.png"))); // NOI18N
        btnConsultar3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Limpar");
        btnConsultar3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 40));

        jPanel19.add(btnConsultar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 160, 40));

        jLabel75.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Título: ");
        jPanel19.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));
        jPanel19.add(txtTituloItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 420, -1));

        jLabel76.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Tipo: ");
        jPanel19.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo do item", "CD", "DVD", "Blu-Ray Disc", " " }));
        jPanel19.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel77.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Preço: ");
        jPanel19.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        txtPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####.##"))));
        jPanel19.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 60, -1));

        jifLocacoes.getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        jDesktopPane1.add(jifLocacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 880, 570));

        pnlBackground.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 860, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        bar(jLabel4);
        jifHome.setVisible(true);
        jifFilmes.setVisible(false);
        jifClientes.setVisible(false);
        jifAtores.setVisible(false);
        jifLocacoes.setVisible(false);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        jPanel4.setBackground(Color.decode("#454545"));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        jPanel4.setBackground(Color.decode("#191919"));
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        bar(jLabel7);
        jifHome.setVisible(false);
        jifFilmes.setVisible(true);
        jifClientes.setVisible(false);
        jifAtores.setVisible(false);
        jifLocacoes.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(Color.decode("#454545"));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(Color.decode("#191919"));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        jPanel4.setBackground(Color.decode("#303030"));
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        jPanel5.setBackground(Color.decode("#303030"));
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        bar(jLabel10);
        jifHome.setVisible(false);
        jifFilmes.setVisible(false);
        jifClientes.setVisible(true);
        jifAtores.setVisible(false);
        jifLocacoes.setVisible(false);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(Color.decode("#454545"));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(Color.decode("#191919"));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        jPanel6.setBackground(Color.decode("#303030"));
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        bar(jLabel1);
        jifHome.setVisible(false);
        jifFilmes.setVisible(false);
        jifClientes.setVisible(false);
        jifAtores.setVisible(true);
        jifLocacoes.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(Color.decode("#454545"));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(Color.decode("#191919"));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        jPanel3.setBackground(Color.decode("#303030"));
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        bar(jLabel18);
        jifHome.setVisible(false);
        jifFilmes.setVisible(false);
        jifClientes.setVisible(false);
        jifAtores.setVisible(false);
        jifLocacoes.setVisible(true);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        jPanel9.setBackground(Color.decode("#454545"));
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        jPanel9.setBackground(Color.decode("#191919"));
    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        jPanel9.setBackground(Color.decode("#303030"));
    }//GEN-LAST:event_jPanel9MousePressed

    private void btnSalvar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvar2MouseEntered
        // TODO add your handling code here:
        btnSalvar2.setBackground(Color.decode("#454545"));
    }//GEN-LAST:event_btnSalvar2MouseEntered

    private void btnSalvar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvar2MouseExited
        // TODO add your handling code here:
        btnSalvar2.setBackground(Color.decode("#232323"));
    }//GEN-LAST:event_btnSalvar2MouseExited

    private void btnSalvar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvar2MousePressed
        // TODO add your handling code here:
        btnSalvar2.setBackground(Color.decode("#303030"));
    }//GEN-LAST:event_btnSalvar2MousePressed

    private void btnCancelar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar2MouseEntered
        // TODO add your handling code here:
        btnCancelar2.setBackground(Color.decode("#454545"));
    }//GEN-LAST:event_btnCancelar2MouseEntered

    private void btnCancelar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar2MouseExited
        // TODO add your handling code here:
        btnCancelar2.setBackground(Color.decode("#232323"));
    }//GEN-LAST:event_btnCancelar2MouseExited

    private void btnCancelar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar2MousePressed
        // TODO add your handling code here:
        btnCancelar2.setBackground(Color.decode("#303030"));
    }//GEN-LAST:event_btnCancelar2MousePressed

    private void btnConsultar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultar2MouseEntered
        // TODO add your handling code here:
        btnConsultar2.setBackground(Color.decode("#454545"));
    }//GEN-LAST:event_btnConsultar2MouseEntered

    private void btnConsultar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultar2MouseExited
        // TODO add your handling code here:
        btnConsultar2.setBackground(Color.decode("#232323"));
    }//GEN-LAST:event_btnConsultar2MouseExited

    private void btnConsultar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultar2MousePressed
        // TODO add your handling code here:
        btnConsultar2.setBackground(Color.decode("#303030"));
    }//GEN-LAST:event_btnConsultar2MousePressed

    private void btnLimpar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpar2MouseEntered
        // TODO add your handling code here:
        btnLimpar2.setBackground(Color.decode("#454545"));
    }//GEN-LAST:event_btnLimpar2MouseEntered

    private void btnLimpar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpar2MouseExited
        // TODO add your handling code here:
        btnLimpar2.setBackground(Color.decode("#232323"));
    }//GEN-LAST:event_btnLimpar2MouseExited

    private void btnLimpar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpar2MousePressed
        // TODO add your handling code here:
        btnLimpar2.setBackground(Color.decode("#303030"));
    }//GEN-LAST:event_btnLimpar2MousePressed

    private void btnSalvar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvar1MouseEntered
        // TODO add your handling code here:
        btnSalvar1.setBackground(Color.decode("#454545"));
    }//GEN-LAST:event_btnSalvar1MouseEntered

    private void btnSalvar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvar1MouseExited
        // TODO add your handling code here:
        btnSalvar1.setBackground(Color.decode("#232323"));
    }//GEN-LAST:event_btnSalvar1MouseExited

    private void btnSalvar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvar1MousePressed
        // TODO add your handling code here:
        btnSalvar1.setBackground(Color.decode("#303030"));
    }//GEN-LAST:event_btnSalvar1MousePressed

    public void bar(JLabel lab){
        jLabel1.setOpaque(false);
        jLabel4.setOpaque(false);
        jLabel7.setOpaque(false);
        jLabel10.setOpaque(false);
        jLabel18.setOpaque(false);
        lab.setOpaque(true);
        jPanel2.repaint();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfaceSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnCancelar1;
    private javax.swing.JPanel btnCancelar2;
    private javax.swing.JPanel btnCancelar3;
    private javax.swing.JPanel btnConsultar;
    private javax.swing.JPanel btnConsultar1;
    private javax.swing.JPanel btnConsultar2;
    private javax.swing.JPanel btnConsultar3;
    private javax.swing.JPanel btnLimpar;
    private javax.swing.JPanel btnLimpar1;
    private javax.swing.JPanel btnLimpar2;
    private javax.swing.JPanel btnLimpar3;
    private javax.swing.JPanel btnSalvar;
    private javax.swing.JPanel btnSalvar1;
    private javax.swing.JPanel btnSalvar2;
    private javax.swing.JPanel btnSalvar3;
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtDataNasc;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbNacionalidade;
    private javax.swing.JInternalFrame jifAtores;
    private javax.swing.JInternalFrame jifClientes;
    private javax.swing.JInternalFrame jifFilmes;
    private javax.swing.JInternalFrame jifHome;
    private javax.swing.JInternalFrame jifLocacoes;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBarraLateral;
    private javax.swing.JTextArea txaSinopse;
    private javax.swing.JTextField txtAtor;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtPreco;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTituloItem;
    // End of variables declaration//GEN-END:variables
}
